name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:iron-ros-base-jammy
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/2024_cavolinia
      - run: sudo apt update
      - run: |
          . /opt/ros/iron/setup.bash
          rosdep update
          rosdep install -i --from-paths src --rosdistro iron -y
          colcon build
